spring:
  application:
    name: server
  ai:
    openai:
      base-url: ${AZURE_OPENAI_ENDPOINT}
      api-key: ${AZURE_OPENAI_API_KEY}
      chat:
        model: ${CHAT_MODEL}
        temperature: 1.0
      embedding:
        dimensions: 1024
        model: ${EMBEDDING_MODEL}
  datasource:
    url: ${POSTGRES_URL}
    password: ${POSTGRES_PASSWORD}
    username: ${POSTGRES_USER}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      ssl:
        enabled: true
  jpa:
    generate-ddl: off
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - profile
              - email
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope:
              - read:user
              - user:emails
app:
  env: dev
  cors:
    allowed-origins: ${ALLOWED_ORIGIN}
  oauth2:
    success-redirect-uri: ${OAUTH2_SUCCESS_REDIRECT_URI:http://localhost:3000/oauth2/callback}
  auth:
    refresh-token-cleanup-cron: "${REFRESH_TOKEN_CLEANUP_CRON:0 0 * * * *}"

jwt:
  secret: ${JWT_SECRET}
